default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: update_check_development
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

test:
  <<: *default
  database: update_check_test
  username: root
  password: password

production:
  <<: *default
  database: update_check_production
  username: update_check
  password: <%= ENV['UPDATE_CHECK_DATABASE_PASSWORD'] %>
